# Generated by Django 5.2.13 on 2026-05-03 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, default="", max_length=60)),
                ("last_name", models.CharField(blank=True, default="", max_length=60)),
                ("bio", models.TextField(blank=True, default="")),
                (
                    "scheduling_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "feedback_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("must_change_password", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_other_freetext", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["is_other_freetext", "sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_other_freetext", True)),
                        fields=("is_other_freetext",),
                        name="uniq_service_category_is_other_freetext_true",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_freetext", models.BooleanField(default=False)),
                (
                    "custom_description",
                    models.CharField(blank=True, default="", max_length=280),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="providerservice_set",
                        to="directory.profile",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_services",
                        to="directory.servicecategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="profiles",
                through="directory.ProviderService",
                to="directory.servicecategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_freetext", False),
                    models.Q(("custom_description", ""), _negated=True),
                    _connector="OR",
                ),
                name="freetext_requires_description",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerservice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_freetext", False)),
                fields=("profile", "category"),
                name="uniq_profile_category_nonfreetext",
            ),
        ),
    ]
