// Shared content for all three design directions.
// Sample directory data for the Sadaqa Jariyah community.

window.SJ_DATA = {
  categories: [
    { slug: 'mentoring', name: 'Mentoring', count: 14 },
    { slug: 'counseling', name: 'Counseling', count: 9 },
    { slug: 'islamic-education', name: 'Islamic Education', count: 22 },
    { slug: 'quran-tutoring', name: 'Qur\u02bcan Tutoring', count: 18 },
    { slug: 'career-advice', name: 'Career Advice', count: 11 },
    { slug: 'arabic-language', name: 'Arabic Language', count: 7 },
    { slug: 'marriage-guidance', name: 'Marriage Guidance', count: 5 },
    { slug: 'other', name: 'Other', count: 13 },
  ],

  members: [
    {
      username: 'maryam',
      name: 'Maryam Abdul-Rahman',
      city: 'Dearborn, MI',
      bio: 'Twenty years teaching tajwid and memorization to women and girls. I take the slow path \u2014 we read until it sounds right, not until the clock runs out.',
      services: ['Qur\u02bcan Tutoring', 'Islamic Education'],
      otherText: null,
      tool: 'Cal.com',
      languages: ['English', 'Arabic'],
    },
    {
      username: 'ibrahim-s',
      name: 'Ibrahim Siddiqui',
      city: 'Toronto, ON',
      bio: 'Software engineer at a healthcare startup. Happy to talk through resumes, technical interviews, and the early years of a tech career with anyone in the community.',
      services: ['Career Advice', 'Mentoring'],
      otherText: null,
      tool: 'Calendly',
      languages: ['English', 'Urdu'],
    },
    {
      username: 'fatimah',
      name: 'Fatimah Diallo',
      city: 'London, UK',
      bio: 'Licensed therapist (UK). Brief check-ins for community members navigating anxiety, grief, or the in-between of faith and modern life. Confidential and free.',
      services: ['Counseling', 'Mentoring'],
      otherText: null,
      tool: 'SavvyCal',
      languages: ['English', 'French', 'Wolof'],
    },
    {
      username: 'yusuf-k',
      name: 'Yusuf Kone',
      city: 'Atlanta, GA',
      bio: 'Imam at a small masjid; PhD in Islamic jurisprudence. I answer questions on \u02bfibadat and family fiqh; I do not give fatwas remotely on complex matters.',
      services: ['Islamic Education'],
      otherText: null,
      tool: 'Calendly',
      languages: ['English', 'Arabic', 'Bambara'],
    },
    {
      username: 'aisha-r',
      name: 'Aisha Rahimi',
      city: 'Bay Area, CA',
      bio: 'Pediatrician and mother of three. I help new parents in the community navigate the first year \u2014 sleep, feeding, when to actually call the doctor.',
      services: ['Other'],
      otherText: 'New-parent guidance and pediatric questions',
      tool: 'Cal.com',
      languages: ['English', 'Dari'],
    },
    {
      username: 'omar-h',
      name: 'Omar Hadid',
      city: 'Houston, TX',
      bio: 'Small business owner. I will sit with anyone thinking of starting something \u2014 a halal kitchen, a tutoring service, a trades business \u2014 and walk through the first ninety days.',
      services: ['Career Advice', 'Mentoring'],
      otherText: null,
      tool: 'Google Calendar',
      languages: ['English', 'Arabic'],
    },
    {
      username: 'khadijah-m',
      name: 'Khadijah Muhammad',
      city: 'Philadelphia, PA',
      bio: 'Qari\u02bcah and Arabic teacher. Beginner-friendly Arabic for adults who feel like they missed the boat in childhood. We start from the alphabet without shame.',
      services: ['Arabic Language', 'Qur\u02bcan Tutoring'],
      otherText: null,
      tool: 'Calendly',
      languages: ['English', 'Arabic'],
    },
    {
      username: 'salim-b',
      name: 'Salim Bashir',
      city: 'Minneapolis, MN',
      bio: 'Family lawyer in Minnesota. Free initial conversations on marriage contracts, custody, and inheritance \u2014 not legal representation, but a place to start understanding your options.',
      services: ['Other'],
      otherText: 'Family law: marriage, custody, inheritance basics',
      tool: 'TidyCal',
      languages: ['English', 'Somali'],
    },
    {
      username: 'noor-a',
      name: 'Noor Ahmadi',
      city: 'Chicago, IL',
      bio: 'Marriage counselor with twelve years of practice. Couples sessions and one-on-ones for those considering, in, or leaving a marriage \u2014 all welcome, no judgment.',
      services: ['Marriage Guidance', 'Counseling'],
      otherText: null,
      tool: 'SavvyCal',
      languages: ['English', 'Farsi'],
    },
  ],

  copy: {
    tagline: 'Find someone in your community to help.',
    sub: 'A directory of community members offering mentorship, counsel, and quiet hours of their time \u2014 in the spirit of sadaqa jariyah, a charity that flows on.',
    cta: 'Schedule with me',
    browse: 'Browse the directory',
    join: 'Offer your time',
    scheduling_note: 'Booking is handled by the member\u2019s scheduling tool. We don\u2019t see your appointment.',
  },
};
